//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySystem
{
    using System;

    public partial class ImportExpense
    {
        public int Id { get; set; }
        public Nullable<int> ImportId { get; set; }
        public string Expense { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual ImportItem ImportItem { get; set; }
    }
}
