//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySystem
{
    using System;

    public partial class ImportItemDetail
    {
        public int Id { get; set; }
        public Nullable<int> ImportId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> Weight { get; set; }
        public string Size { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual ImportItem ImportItem { get; set; }
        public virtual Item Item { get; set; }
    }
}
