//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new ObservableListSource<OrderDetail>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public string OrderDate { get; set; }
        public string DeliveryDate { get; set; }
        public Nullable<bool> Delivered { get; set; }
        public Nullable<bool> Approved { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ObservableListSource<OrderDetail> OrderDetails { get; set; }
    }
}
