//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producer
    {
        public Producer()
        {
            this.ProductionDetails = new ObservableListSource<ProductionDetail>();
        }
    
        public int Id { get; set; }
        public string Producer1 { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public string Contact2 { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ObservableListSource<ProductionDetail> ProductionDetails { get; set; }
    }
}
